### ISSUE TITLE
Requiring unknown module "SGListView".  

### ISSUE THREAD

**Issue by udfalkso** [sghiassy/react-native-sglistview#1]
Hi @sghiassy.  Thanks for building this!  Looking forward to trying it out.  Sorry to be the first issue.... 

I'm getting an error when trying to require SGListView
![screen shot 2015-08-07 at 6 01 45 pm](https://cloud.githubusercontent.com/assets/2029383/9146864/6287f460-3d2e-11e5-8072-98514ce6d8c6.png)

I installed via npm install react-native-sglistview --save.  I tried restarting the packager, xcode, etc.  Did a project -> clean.  

Any idea what I might be doing wrong?  Thanks!

**Comment by sghiassy** [comment]
Did you import the package into the file?

```
var SGListView = require('react-native-sglistview');
```

**Comment by sghiassy** [comment]
This probably stems from the typo in the README doc. I fixed that too

**Comment by udfalkso** [comment]
Yup, got it from the README, I should have known.  Thanks.

Now I'm getting this error.  

Warning: React.createElement: type should not be null or undefined. It should be a string (for DOM elements) or a ReactClass (for composite components).
WarningBox.js:61 Warning: Only functions or strings can be mounted as React components.
index.js:100 error Error: Invariant Violation: Expected a component class, got undefined.
    at invariant (http://localhost:8081/index.ios.bundle:2070:9)
    at http://localhost:8081/index.ios.bundle:6811:1
    at Object.getComponentClassForElement (http://localhost:8081/index.ios.bundle:6363:45)
    at ReactCompositeComponentMixin._processProps (http://localhost:8081/index.ios.bundle:8839:36)
    at ReactCompositeComponentMixin.mountComponent (http://localhost:8081/index.ios.bundle:8546:22)
    at ReactPerf.measure.wrapper [as mountComponent](http://localhost:8081/index.ios.bundle:5410:13)
    at Object.ReactReconciler.mountComponent (http://localhost:8081/index.ios.bundle:5479:29)
    at ReactCompositeComponentMixin._updateRenderedComponent (http://localhost:8081/index.ios.bundle:9169:32)
    at ReactCompositeComponentMixin._performComponentUpdate (http://localhost:8081/index.ios.bundle:9132:6)
    at ReactCompositeComponentMixin.updateComponent (http://localhost:8081/index.ios.bundle:9052:6)

**Comment by sghiassy** [comment]
That looks like an error that the require statement is not importing the framework. My guess is if you `console.log(SGListView)` you will get `undefined`. 

Try restarting `packager`

**Comment by udfalkso** [comment]
No luck.  I tried ./node_modules/react-native/packager/packager.sh --reset-cache too but still getting the same error.  Thanks for your help, I will have to experiment more later.

**Comment by sghiassy** [comment]
I usually just quit packager and restart it. 

Also check to make sure the files are actually there. You should see

```
node_modules/react-native-sglistview
```

Lastly, I tested the README steps again in a small test app, and they worked for me. Sorry to hear you're having problems

**Comment by udfalkso** [comment]
Got it to work :)

I had to remove SGListView from the var { View, Image, ... } = React statement on top.  Thanks again for your help.

**Comment by udfalkso** [comment]
Now it's working quite nicely btw!  I haven't managed to crash my app that previously crashed rather easily while scrolling.
